name: VarMain
version: 1.5
main: main.CorePlugin
api-version: 1.21
depend: [ProtocolLib]
commands:
  startdialog:
    description: Start test dialog with NPC
    usage: /startdialog
  loaddialogs:
    description: Загружает все диалоги и создаёт NPC
    usage: /loaddialogs
  loadUI:
    descryption: Загружает конфиг UI общения с NPC
    usage: /loadUI
  loadCfgNPC:
    description: Загружает конифгурацию npc
    usage: loadCfgNPC
  respnnpc:
    description: Респавнит нпс по ID из config.yaml
    usage: /respnnpc