name: VarMain
version: 1.4
main: main.CorePlugin
api-version: 1.21
depend: [ProtocolLib, Citizens]
commands:
  startdialog:
    description: Start test dialog with NPC
    usage: /startdialog
  loaddialogs:
    description: Загружает все диалоги и создаёт NPC
    usage: /loaddialogs